config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users do
    resources :filters
  end

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout

  resources :dogs

  resources :conversations do
    resources :messages
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :email, :zipcode,  presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 4 }
  validates :name, length: { minimum: 2 }

  has_many :dogs
  has_secure_password

  has_attached_file :avatar, :default_url => "/images/normal/missinguser.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_many :conversations, :foreign_key => :sender_id
  has_many :filters
  delegate :breeds, :sizes, :plays, :ages, :personalities, :blocked_user_ids, :genders, :locations, to: :filters
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
  end

  def show
    @user = User.find(params[:id])
    @filters=@user.filters.all

    @dogs = Dog.all
    @filters.each do |filter|
      @dogs = filter.filter(@dogs)
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to user_path
      flash[:notice] = "Your information was successfully updated."
    else
      render :edit
      flash[:alert] = "Your information could not be saved."
    end
  end


  private
  def user_params
    params.require(:user).permit(
    :name,
    :email,
    :password,
    :password_confirmation,
    :age,
    :zipcode,
    :gender,
    :bio,
    :avatar
    )
  end

end

app/views/users/edit.html.erb
<div class="ui segment">
  <h1>Editing <%= @user.name %>'s Profile</h1>
</div>

<div class="ui form segment">
  <%= form_for @user, url: user_path(@user), html: {class: "ui form"} do |f| %>

  <%= render 'shared/errors', object: @user %>

  <div class="three fields">
    <div class="field">
      <%= f.label :name %>
      <div class="field">
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="field">
      <%= f.label :email %>
      <div class="field">
        <%= f.email_field :email %>
      </div>
    </div>

    <div class="field">
      <%= f.label :zipcode %>
      <div class="field">
        <%= f.text_field :zipcode %>
      </div>
    </div>
  </div>

  <div class="two fields">
    <div class="field">
      <label>Gender</label>
      <div class="ui selection dropdown">
        <div class="default text">Gender</div>
        <i class="dropdown icon"></i>
        <%= f.text_field :gender, type: "hidden" %>
        <div class="menu">
          <div class="item" data-value="Female">Female</div>
          <div class="item" data-value="Male">Male</div>
        </div>
      </div>
    </div>

    <div class="field">
      <%= f.label :Age %>
      <div class="field">
        <%= f.text_field :age %>
      </div>
    </div>

  </div>

  <div class="field">
    <%= f.label "Tell Us More About You" %>
    <div class="field">
      <%= f.text_area :bio %>
    </div>
  </div>

  <div class="field">
    <%= f.label "Upload a picture" %>
    <div class="field">
      <%= f.file_field :avatar %>
    </div>
  </div>

  <%= f.submit "Submit", class: "ui submit button" %>

  <% end  %>
</div>

app/views/users/show.html.erb
<div class="ui segment">
  <a class="ui ribbon label"><%= @user.name %></a>

  <div class="ui small circular image">
    <%= image_tag(@user.avatar) %>
  </div>

  <% if current_user %>
  <div class="ui segment">
    <div class="content" data-user-zipcode="<%= @user.zipcode %>">
      <p><%= @user.email %></p>
      <p><%= @user.zipcode %></p>
      <p><%= @user.age %></p>
      <p><%= @user.gender %></p>
      <p><%= @user.bio %></p>
    </div>
  </div>
  <% end %>

  <% if current_user && current_user.id == @user.id %>
  <div class="ui button">
    <%= link_to "Edit", edit_user_path(@user) %>
  </div>
  <% end %>
</div>

<div class="ui eight wide segment">
  <% if current_user && current_user.id == @user.id  %>
  <a class="ui ribbon label"><%= @user.name %>'s Potential Matches</a>
  <div class="ui segment">
    <%= @dogs.map(&:name) %>
  </div>
  <% end  %>

  <a class="ui ribbon label"><%= @user.name %>'s Dog Preferences</a>
  <div class="ui segment">
    <% @filters.each do |filter| %>
      <%= filter.type %>: <%= filter.content %>
    <% end %>
  </div>

  <% if current_user && current_user.id == @user.id  %>
  <div class="ui button">
    <%= link_to "Change Preferences", new_user_filter_path(@user) %>
  </div>
  <% end %>
</div>


<div class="ui segment">
  <a class="ui ribbon label"><%= @user.name %>'s Dogs</a>
  <% @user.dogs.in_groups(3) do |column_dogs| %>
  <div class="column">
    <% column_dogs.each do |dog| %>
    <% break if dog.nil? %>
    <div class="ui card field">
      <div class="content">
        <div class="header" data-dog-id ="<%= dog.id %>">
          <div class="ui avatar image">
            <%= image_tag(dog.image) %>
          </div>
          <%= dog.name %>
        </div>
        <div class="description">
          <%= dog.bio %>
        </div>
      </div>

      <div class="ui bottom attached segment">
        <% if current_user && current_user.id == @user.id %>
        <div class="ui inverted teal button">
          <%= link_to "Edit", edit_dog_path(dog) %>
        </div>
        <div class="ui button">
          <%= link_to 'Delete Dog', dog_path(dog), method: :delete, data: {confirm: "Are you sure?"}  %>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
    <div class ="one wide field"></div>
  </div>
  <% end %>
</div>

<% if current_user && current_user.id == @user.id %>
<div class="column padding">
  <div class="ui teal inverted button">
    <%= link_to "Add Dog", new_dog_path %>
  </div>
</div>
<% end %>

<div class="header">
  <h3>Dog Parks in Your Area</h3>
</div>

<div class="ui segment two column grid">
  <div class="column">
    <div id="map-canvas" style="width: 300px; height: 300px;"></div>
  </div>
  <div class="column">
    <div class="ui divided list" id="map-segment">
    </div>
  </div>
</div>

<script charset="utf-8" id="dog-modal" text="text/x-handlebars-template">
<div class="ui modal">
  <i class="close icon"></i>
  <div class="header">{{name}}</div>
  <div class="content">
    <div class="ui medium circular image">
      <img src ={{image}}>
    </div>
    <div class="description">
      <h3>A Little Bit About Me</h3>
      <p>{{bio}}</p>
      <ul>
        <li>Breed:{{breed}}</li>
        <li>Gender: {{gender}}</li>
        <li>Play Type:{{play}}</li>
        <li>Personality Type: {{personality}}</li>
      </ul>
    </div>
  </div>
  <div class="actions">
    <div class="ui button">OK</div>
  </div>
</div>
</script>