config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users do
    resources :filters
  end

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout

  resources :dogs

  resources :conversations do
    resources :messages
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Puppy Love</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="ui inverted fixed menu navbar page grid">
    <% home_page = is_active?(root_path) %>
    <%= link_to "Puppy Love", root_path, class: "brand item #{home_page}" %>
    <div class="right menu">
      <% if current_user %>
        <% profile_page = is_active?(user_path(current_user)) %>
          <%= link_to current_user.name, user_path(current_user), class: "ui item #{profile_page}" %>
        <% conversation_page = is_active?(conversations_path) %>
          <%= link_to "Mailbox", conversations_path, class: "item #{conversation_page}" %>
        <% search_page = is_active?(dogs_path) %>
          <%= link_to "Search", dogs_path, class: "item #{search_page}" %>
          <%= link_to "Sign Out", signout_path, class: "item"%>
      <% else %>
        <% sign_up_page = is_active?(signup_path) %>
          <%= link_to 'Sign Up', signup_path, class: "item #{sign_up_page}" %>
        <% sign_in_page = is_active?(signin_path) %>
          <%= link_to "Sign-In", signin_path, class: "item #{sign_in_page}" %>
        <%= link_to "Search", dogs_path, class: "item #{search_page}" %>
      <% end %>
    </div>
  </div>

  <% if notice %>
    <div class="ui positive message">
      <i class="close icon"></i>
      <div class="header">
        <p id="notice" class="text-center"><%= notice %></p>
      </div>
    </div>
  <% end %>

  <% if alert %>
  <div class="ui error message">
    <i class="close icon"></i>
    <div class="header">
      <p id="notice" class="text-center"><%= alert %></p>
    </div>
  </div>
  <% end %>

<%= yield %>

<script charset="utf-8">
  $('.ui.dropdown').dropdown();
</script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places"></script>
</body>
</html>